source :rubygems

gem 'gisele-vm', :path => "../.."
gem 'sinatra',   '~> 1.3'
gem 'thin', '~> 1.3'
gem "sequel", "~> 3.33"

platform 'mri' do
  gem "sqlite3", "~> 1.3"
end
platform 'jruby' do
  gem "jdbc-sqlite3", "~> 3.7"
end
